name: Issue Comment Management

on:
  issue_comment:
    types: [created]

jobs:
  manage_issue_comment:
    runs-on: ubuntu-latest

    steps:
    - name: Check if comment contains specific text
      if: contains(github.event.comment.body, 'I do not have a login for this website so contributions are welcome. :)')
      run: |
        echo "Comment contains the specified text."

        # Add labels to the issue
        curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels \
          -d '{"labels":["help wanted", "no account"]}'

        # Unassign the current user from the issue
        curl -s -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees \
          -d '{"assignees":["${{ github.actor }}"]}'

        # Assign the issue creator to the issue
        curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees \
          -d '{"assignees":["${{ github.event.issue.user.login }}"]}'
